name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: adambirds/docker-compose-action@v1.3.0
      with:
        compose-file: "./docs/postgres_local/docker-compose.yaml"

    - name: Build
      run: cargo build --verbose
      
    - name: Migrate & Test
      run: make test
