name: Rust Unit Test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Diesel
      run: cargo install diesel_cli --no-default-features --features postgres

    - name: set secret
      run: |
        echo "$DOTENV" > .env
      env:
        DOTENV: ${{secrets.DOTENV}}

    - uses: adambirds/docker-compose-action@v1.3.0
      with:
        compose-file: "./docs/postgres_local/docker-compose.yaml"

    - name: Migrate & Test
      run: | 
        sleep 2;
        diesel migration run;
        sleep 2;
        cargo test --verbose
        

    - name: Build
      run: cargo build --verbose
